libcluon: cluon::EnvelopeToJSON Class Reference
cluon::EnvelopeToJSON Class Reference
#include <EnvelopeToJSON.hpp>
Public Member Functions
EnvelopeToJSON ()=default
int32_t setMessageSpecification (const std::string &ms) noexcept
std::string getJSONFromProtoEncodedEnvelope (const std::string &protoEncodedEnvelope) noexcept
std::string getJSONFromEnvelope (cluon::data::Envelope &envelope) noexcept
Detailed Description
This class transforms a given Envelope into a JSON representation for its contained payload.
Constructor & Destructor Documentation
cluon::EnvelopeToJSON::EnvelopeToJSON () default
Member Function Documentation
std::string cluon::EnvelopeToJSON::getJSONFromEnvelope (cluon::data::Envelope & envelope) noexcept
This method transforms the given Envelope to JSON.
Parameters
envelope Envelope.
Returns
JSON representation from given Envelope using the given message specification.
References cluon::GenericMessage::accept(), cluon::GenericMessage::createFrom(), cluon::FromProtoVisitor::decodeFrom(), and retVal.
std::string cluon::EnvelopeToJSON::getJSONFromProtoEncodedEnvelope (const std::string & protoEncodedEnvelope) noexcept
This method transforms the given Proto-encoded Envelope to JSON. The Proto-encoded envelope might be preceded with a 5-bytes OD4-header (optional).
Parameters
protoEncodedEnvelope Proto-encoded Envelope.
Returns
JSON representation from given Proto-encoded Envelope using the given message specification.
References cluon::FromProtoVisitor::decodeFrom(), cluon::extractEnvelope(), and retVal.
int32_t cluon::EnvelopeToJSON::setMessageSpecification (const std::string & ms) noexcept
This method sets the message specification to be used for interpreting a given Proto-encoded Envelope.
Parameters
ms Message specification following the ODVD format.
Returns
-1 in case of invalid message specification; otherwise, number of successfully parsed messages from given message specification.
References mm, cluon::MessageParser::parse(), and retVal.