libcluon: cluon::MetaMessage Class Reference
cluon::MetaMessage Class Reference
#include <MetaMessage.hpp>
Classes
class MetaField
Public Member Functions
MetaMessage () noexcept
MetaMessage (const MetaMessage &)=default
MetaMessage (MetaMessage &&)=default
MetaMessage & operator= (const MetaMessage &)=default
MetaMessage & operator= (MetaMessage &&)=default
MetaMessage & add (MetaField &&mf) noexcept
const std::vector< MetaField > & listOfMetaFields () const noexcept
void accept (const std::function< void(const MetaMessage &)> &visit)
std::string packageName () const noexcept
MetaMessage & packageName (const std::string &v) noexcept
std::string messageName () const noexcept
MetaMessage & messageName (const std::string &v) noexcept
int32_t messageIdentifier () const noexcept
MetaMessage & messageIdentifier (int32_t v) noexcept
Detailed Description
This class provides a generic description for a message. It is internally used during the processing of message specifications to generate targets like C++ or .proto files.
Constructor & Destructor Documentation
MetaMessage() [1/3]
cluon::MetaMessage::MetaMessage () noexcept
MetaMessage() [2/3]
cluon::MetaMessage::MetaMessage (const MetaMessage &) default
MetaMessage() [3/3]
cluon::MetaMessage::MetaMessage (MetaMessage &&) default
Member Function Documentation
accept()
void cluon::MetaMessage::accept (const std::function< void(const MetaMessage &)> & visit)
This method can be used to visit this instance and propagate information details about the contained fields.
Parameters
visit std::function object to be called to visit this MetaMessage.
add()
MetaMessage & cluon::MetaMessage::add (MetaMessage::MetaField && mf) noexcept
This method adds a metafield to this meta message.
Parameters
mf Meta field to be added.
Returns
Reference to this instance.
References mf.
listOfMetaFields()
const std::vector< MetaMessage::MetaField > & cluon::MetaMessage::listOfMetaFields () const noexcept
This method returns a vector of current meta fields.
Returns
Meta fields from this meta message.
Referenced by cluon::GenericMessage::createFrom().
messageIdentifier() [1/2]
int32_t cluon::MetaMessage::messageIdentifier () const noexcept
Returns
Message identifier.
Referenced by cluon::GenericMessage::ID(), and cluon::MessageParser::parse().
messageIdentifier() [2/2]
MetaMessage & cluon::MetaMessage::messageIdentifier (int32_t v) noexcept
This method sets the message identifier.
Parameters
v Message identifier for this message.
Returns
Reference to this instance.
messageName() [1/2]
std::string cluon::MetaMessage::messageName () const noexcept
Returns
Message name.
Referenced by cluon::GenericMessage::createFrom(), cluon::GenericMessage::LongName(), and cluon::MessageParser::parse().
messageName() [2/2]
MetaMessage & cluon::MetaMessage::messageName (const std::string & v) noexcept
This method sets the message name.
Parameters
v Message name for this message.
Returns
Reference to this instance.
operator=() [1/2]
MetaMessage& cluon::MetaMessage::operator= (const MetaMessage &) default
operator=() [2/2]
MetaMessage& cluon::MetaMessage::operator= (MetaMessage &&) default
packageName() [1/2]
std::string cluon::MetaMessage::packageName () const noexcept
Returns
Package name.
Referenced by cluon::GenericMessage::LongName(), and cluon::MessageParser::parse().
packageName() [2/2]
MetaMessage & cluon::MetaMessage::packageName (const std::string & v) noexcept
This method sets the package name.
Parameters
v Package name for this message.
Returns
Reference to this instance.