libcluon: cluon::MessageFromProtoDecoder Class Reference
cluon::MessageFromProtoDecoder Class Reference
#include <MessageFromProtoDecoder.hpp>
Public Member Functions
MessageFromProtoDecoder ()=default
~MessageFromProtoDecoder ()=default
MessageFromProtoDecoder & operator= (const MessageFromProtoDecoder &other) noexcept
void decodeFrom (std::istream &in) noexcept
void preVisit (uint32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Detailed Description
This class decodes a given message from Proto format.
Constructor & Destructor Documentation
cluon::MessageFromProtoDecoder::MessageFromProtoDecoder () default
cluon::MessageFromProtoDecoder::~MessageFromProtoDecoder () default
Member Function Documentation
void cluon::MessageFromProtoDecoder::decodeFrom (std::istream & in) noexcept
This method decodes a given istream into Proto.
Parameters
in istream to decode.
References cluon::EIGHT_BYTES, cluon::FOUR_BYTES, cluon::LENGTH_DELIMITED, retVal, and cluon::VARINT.
Referenced by cluon::EnvelopeToJSON::getJSONFromEnvelope(), cluon::EnvelopeToJSON::getJSONFromProtoEncodedEnvelope(), and visit().
MessageFromProtoDecoder & cluon::MessageFromProtoDecoder::operator= (const MessageFromProtoDecoder & other) noexcept
void cluon::MessageFromProtoDecoder::postVisit () noexcept
void cluon::MessageFromProtoDecoder::preVisit (uint32_t id, const std::string & shortName, const std::string & longName) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, char & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, float & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, double & v) noexcept
void cluon::MessageFromProtoDecoder::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) noexcept
template<typename T > void cluon::MessageFromProtoDecoder::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) inline noexcept
References decodeFrom().