libcluon: cluon::MessageToProtoEncoder Class Reference
cluon::MessageToProtoEncoder Class Reference
#include <MessageToProtoEncoder.hpp>
Public Member Functions
MessageToProtoEncoder ()=default
~MessageToProtoEncoder ()=default
std::string encodedData () const noexcept
void preVisit (uint32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Detailed Description
This class encodes a given message in Proto format.
Constructor & Destructor Documentation
cluon::MessageToProtoEncoder::MessageToProtoEncoder () default
cluon::MessageToProtoEncoder::~MessageToProtoEncoder () default
Member Function Documentation
std::string cluon::MessageToProtoEncoder::encodedData () const noexcept
Returns
Encoded data in Proto format.
Referenced by visit().
void cluon::MessageToProtoEncoder::postVisit () noexcept
void cluon::MessageToProtoEncoder::preVisit (uint32_t id, const std::string & shortName, const std::string & longName) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, char & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) noexcept
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, float & v) noexcept
References cluon::FOUR_BYTES.
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, double & v) noexcept
References cluon::EIGHT_BYTES.
void cluon::MessageToProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) noexcept
References fieldIdentifier(), and cluon::LENGTH_DELIMITED.
template<typename T > void cluon::MessageToProtoEncoder::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) inline noexcept
References encodedData(), fieldIdentifier(), cluon::LENGTH_DELIMITED, and cluon::VARINT.