libcluon: cluon::MessageAsProtoEncoder Class Reference
cluon::MessageAsProtoEncoder Class Reference
#include <MessageToProtoEncoder.hpp>
Public Member Functions
MessageAsProtoEncoder ()=default
~MessageAsProtoEncoder ()=default
std::string encodedData () noexcept
void visit (uint32_t id, bool &v) noexcept
void visit (uint32_t id, char &v) noexcept
void visit (uint32_t id, int8_t &v) noexcept
void visit (uint32_t id, uint8_t &v) noexcept
void visit (uint32_t id, int16_t &v) noexcept
void visit (uint32_t id, uint16_t &v) noexcept
void visit (uint32_t id, int32_t &v) noexcept
void visit (uint32_t id, uint32_t &v) noexcept
void visit (uint32_t id, int64_t &v) noexcept
void visit (uint32_t id, uint64_t &v) noexcept
void visit (uint32_t id, float &v) noexcept
void visit (uint32_t id, double &v) noexcept
void visit (uint32_t id, const std::string &v) noexcept
void preVisit (uint32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
Detailed Description
This class encodes a given message in Proto format.
Constructor & Destructor Documentation
cluon::MessageAsProtoEncoder::MessageAsProtoEncoder () default
cluon::MessageAsProtoEncoder::~MessageAsProtoEncoder () default
Member Function Documentation
std::string cluon::MessageAsProtoEncoder::encodedData () noexcept
Returns
Encoded data in Proto format.
Referenced by visit().
void cluon::MessageAsProtoEncoder::postVisit () noexcept
void cluon::MessageAsProtoEncoder::preVisit (uint32_t id, const std::string & shortName, const std::string & longName) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, bool & v) noexcept
Referenced by visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, char & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, int8_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, uint8_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, int16_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, uint16_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, int32_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, uint32_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, int64_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, uint64_t & v) noexcept
void cluon::MessageAsProtoEncoder::visit (uint32_t id, float & v) noexcept
References cluon::FOUR_BYTES.
void cluon::MessageAsProtoEncoder::visit (uint32_t id, double & v) noexcept
References cluon::EIGHT_BYTES.
void cluon::MessageAsProtoEncoder::visit (uint32_t id, const std::string & v) noexcept
References cluon::LENGTH_DELIMITED.
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, char & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, float & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, double & v) noexcept
References visit().
void cluon::MessageAsProtoEncoder::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) noexcept
References fieldIdentifier(), and visit().
template<typename T > void cluon::MessageAsProtoEncoder::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) inline noexcept
References encodedData(), fieldIdentifier(), cluon::LENGTH_DELIMITED, and cluon::VARINT.