libcluon: cluon::JSONVisitor Class Reference
cluon::JSONVisitor Class Reference
#include <JSONVisitor.hpp>
Public Member Functions
JSONVisitor (bool withOuterCurlyBraces=true, const std::map< uint32_t, bool > &mask={}) noexcept
std::string json () const noexcept
void preVisit (uint32_t id, const std::string &shortName, const std::string &longName) noexcept
void postVisit () noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, bool &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, char &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint8_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint16_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint32_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, int64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, uint64_t &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, float &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, double &v) noexcept
void visit (uint32_t id, std::string &&typeName, std::string &&name, std::string &v) noexcept
template<typename T >
void visit (uint32_t &id, std::string &&typeName, std::string &&name, T &value) noexcept
std::string encodeBase64 (const std::string &input) const noexcept
Detailed Description
This class provides a visitor to transform a message into JSON:
MyMessage msg;
// Set some values in msg.
cluon::JSONVisitor j;
msg.accept(j);
std::cout << j.json() << std::endl;
Constructor & Destructor Documentation
cluon::JSONVisitor::JSONVisitor (bool withOuterCurlyBraces = true, const std::map< uint32_t, bool > & mask = {}) noexcept
Constructor.
Parameters
withOuterCurlyBraces Include the outer curly braces.
mask Map describing which fields to render. If empty, all fields will be emitted; individual field identifiers can be masked setting them to false.
Member Function Documentation
std::string cluon::JSONVisitor::encodeBase64 (const std::string & input) const noexcept
This method returns the base64-encoded representation for the given input.
Parameters
input to encode as base64
Returns
base64 encoded input.
References retVal.
Referenced by visit().
std::string cluon::JSONVisitor::json () const noexcept
Returns
JSON-encoded data.
References retVal.
Referenced by visit().
void cluon::JSONVisitor::postVisit () noexcept
void cluon::JSONVisitor::preVisit (uint32_t id, const std::string & shortName, const std::string & longName) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, bool & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, char & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int8_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint8_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int16_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint16_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int32_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint32_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, int64_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, uint64_t & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, float & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, double & v) noexcept
void cluon::JSONVisitor::visit (uint32_t id, std::string && typeName, std::string && name, std::string & v) noexcept
References encodeBase64().
template<typename T > void cluon::JSONVisitor::visit (uint32_t & id, std::string && typeName, std::string && name, T & value) inline noexcept
References json().