libcluon: cluon::SharedMemory Class Reference
cluon::SharedMemory Class Reference
#include <SharedMemory.hpp>
Public Member Functions
SharedMemory (const std::string &name, uint32_t size=0) noexcept
~SharedMemory () noexcept
void lock () noexcept
void unlock () noexcept
void wait () noexcept
void notifyAll () noexcept
char * data () noexcept
uint32_t size () const noexcept
const std::string name () const noexcept
bool valid () noexcept
Constructor & Destructor Documentation
cluon::SharedMemory::SharedMemory (const std::string & name, uint32_t size = 0) noexcept
Constructor.
Parameters
name Name of the shared memory area; must start with / and must not be longer than NAME_MAX (255) on POSIX or PATH_MAX on WIN32. If the name is missing a leading '/' or is longer than 255, it will be adjusted accordingly.
size of the shared memory area to create; if size is 0, the class tries to attach to an existing area.
References retVal.
cluon::SharedMemory::~SharedMemory () noexcept
References unlock().
Member Function Documentation
char * cluon::SharedMemory::data () noexcept
Returns
Pointer to the raw shared memory or nullptr in case of invalid shared memory.
void cluon::SharedMemory::lock () noexcept
This method locks the shared memory area.
Referenced by wait().
const std::string cluon::SharedMemory::name () const noexcept
Returns
Name the shared memory area.
void cluon::SharedMemory::notifyAll () noexcept
This method notifies all threads waiting on the shared condition.
uint32_t cluon::SharedMemory::size () const noexcept
Returns
The size of the shared memory area.
void cluon::SharedMemory::unlock () noexcept
This method unlocks the shared memory area.
Referenced by wait(), and ~SharedMemory().
bool cluon::SharedMemory::valid () noexcept
Returns
True if the shared memory area is existing and usable.
void cluon::SharedMemory::wait () noexcept
This method waits for being notified from the shared condition.
References lock(), and unlock().