libcluon: cluon::TerminateHandler Class Reference
cluon::TerminateHandler Class Reference
#include <TerminateHandler.hpp>
Public Member Functions
~TerminateHandler ()=default
Static Public Member Functions
static TerminateHandler & instance () noexcept
Public Attributes
std::atomic< bool > isTerminated {false}
Constructor & Destructor Documentation
~TerminateHandler()
cluon::TerminateHandler::~TerminateHandler () default
Member Function Documentation
instance()
static TerminateHandler& cluon::TerminateHandler::instance () inline static noexcept
Define singleton behavior using static initializer (cf. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf, Sec. 6.7.4).
Returns
singleton for an instance of this class.
Referenced by cluon::cluon_handleExit(), cluon::cluon_handleSignal(), cluon::TCPServer::isRunning(), cluon::UDPReceiver::isRunning(), cluon::TCPConnection::isRunning(), and cluon::OD4Session::timeTrigger().
Member Data Documentation
isTerminated
std::atomic<bool> cluon::TerminateHandler::isTerminated {false}
Referenced by cluon::cluon_handleExit(), cluon::cluon_handleSignal(), cluon::TCPServer::isRunning(), cluon::UDPReceiver::isRunning(), and cluon::TCPConnection::isRunning().